# Generated by Django 4.0 on 2023-03-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcuts',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
